#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

rm ~/.bash_profile ~/.gitconfig ~/.gitignore_global ~/.vimrc

ln -s $DIR/.bash_profile ~/.bash_profile
ln -s $DIR/.gitconfig ~/.gitconfig
ln -s $DIR/.gitignore_global ~/.gitignore_global
ln -s $DIR/.vimrc ~/.vimrc
ln -s $DIR/.tmux.conf ~/.tmux.conf
ln -s $DIR/.pip ~/.pip
