#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

ln -s $DIR/.bash_profile ~/.bash_profile
ln -s $DIR/.gitconfig ~/.gitconfig
ln -s $DIR/.gitconfig_global ~/.gitconfig_global
ln -s $DIR/.vimrc ~/.vimrc
